[hosts]
177.71.150.163 ansible_user=ubuntu ansible_ssh_private_key_file=/home/carlos/teste.pem

[agents]
18.231.140.247 ansible_user=ubuntu ansible_ssh_private_key_file=/home/carlos/teste.pem
18.230.215.83 ansible_user=ubuntu ansible_ssh_private_key_file=/home/carlos/teste.pem
56.125.130.44 nsible_user=ubuntu ansible_ssh_private_key_file=/home/carlos/teste.pem
54.233.42.253 ansible_user=ubuntu ansible_ssh_private_key_file=/home/carlos/teste.pem