---
- name: Deploy stack zabbix server
  hosts: zabbix_server
  become: true
  roles:
    - monitoring

- name: Instala Zabbix Agent nas instâncias monitoradas
  hosts: zabbix_agent
  become: true
  roles:
    - zabbix-agent